- charts/milvus/Chart.yaml
- charts/milvus/templates/attu-deployment.yaml
- charts/milvus/values.yaml
This adds pod labels to pods created as part of the attu deployment.
> [milvus] Add podLabels option for attu.

- charts/milvus/Chart.yaml
- charts/milvus/templates/attu-deployment.yaml
The labels specified in the global values section are currently not being applied to the Attu deployment. This modification will ensure that the labels defined by users are incorporated into the Attu deployment
> [Milvus] Add labels to attu component

- charts/milvus/Chart.yaml
- charts/milvus/templates/attu-deployment.yaml
Include nodeSelectors in the Attu deployment to limit pod scheduling to specific dedicated nodes.
> [Milvus] Add nodeSelector to Attu deployment

- charts/milvus/Chart.yaml
- charts/milvus/templates/datanode-deployment.yaml
- charts/milvus/templates/indexnode-deployment.yaml
- charts/milvus/templates/proxy-deployment.yaml
- charts/milvus/templates/querynode-deployment.yaml
- charts/milvus/values.yaml
Hi !
If users configure HPA on their side to control index/data/query/proxy pods Deployments, we need to remove the replicas field to avoid the bad well-known HPA behavior in case of rollout-update/apply.
https://github.com/kubernetes/kubernetes/issues/25238
This feature will be necessary when HPA will be available in this chart again as well :)
Fix [#16](https://github.com/zilliztech/milvus-helm/issues/16)
Regards,
> [milvus] allow to unset replicas field in autoscalable deployments

- charts/milvus/Chart.yaml
- charts/milvus/README.md
- charts/milvus/templates/proxy-deployment.yaml
- charts/milvus/templates/proxy-tls-secret.yaml
- charts/milvus/values.yaml
> [milvus] 22 proxy tls support

- .github/workflows/lint-test.yml
- charts/milvus/README.md
Add docs for the minimal standalone
> [milvus] <docs>: Add docs for the minimal standalone

- charts/milvus/values.yaml
Users will have questions when using the external Kafak. Add more comments.
> [Milvus] <docs>: add more comments to externalKafka parameter

- charts/milvus/values.yaml
Removes and updates the wrong minIO readme reference link in Milvus value file 
> [Milvus] <readme>: update minio readme reference link in milvus value file

- charts/milvus/Chart.yaml
- charts/milvus/values.yaml
In order to ensure proper coordination and support for Scann index we need this fix. A new Scann index is essential for enhancing performance, scalability, customisation and competitiveness which is missing in older version of attu.
> [milvus-4.1.18] Adding support for ScaNN index

- charts/milvus/Chart.yaml
- charts/milvus/README.md
- charts/milvus/values.yaml
Author - @Rachit-Chaudhary11
This update will allow for better scalability and flexibility in managing the users access to milvus instance. Presently this limit is set to 100 users per milvus instance and there is no way to increase / decrease the users limit to milvus instance.
> [milvus-4.1.18] Enhancement: Reset Default Max Limit on Users per Milvus Instance

- charts/milvus/Chart.yaml
- charts/milvus/README.md
- charts/milvus/templates/datanode-deployment.yaml
- charts/milvus/templates/indexnode-deployment.yaml
- charts/milvus/templates/proxy-deployment.yaml
- charts/milvus/templates/querynode-deployment.yaml
- charts/milvus/values.yaml
Allow to specify the Deployment' strategy for "node" components (indexNode, queryNode, dataNode, proxyNode).
Usefull when you want more control on the RollingUpdate process (maxUnavailable, maxSurge...).
> [milvus] add Deployment strategy configuration

- charts/milvus/Chart.yaml
- charts/milvus/README.md
- charts/milvus/templates/datacoord-deployment.yaml
- charts/milvus/templates/indexcoord-deployment.yaml
- charts/milvus/templates/mixcoord-deployment.yaml
- charts/milvus/templates/querycoord-deployment.yaml
- charts/milvus/templates/rootcoord-deployment.yaml
- charts/milvus/values.yaml
By enabling this feature, Milvus Instances will be resilient to failures, ensuring continuous availability and reliability for users. The implementation includes fault-tolerant mechanisms and redundancy configurations to mitigate downtime and main uninterrupted service in the event of node failures or network issues. Overall, this enhancement enhances the robustness and performance of Milvus, providing a more resilient infrastructure for data storage and retrieval.
> [milvus-4.1.18] Enabling High Availability for Milvus 

- charts/milvus/Chart.yaml
- charts/milvus/README.md
- charts/milvus/values.yaml
This enhancement empowers administrators to dynamically adjust the maximum number of roles allowed within the system, providing greater flexibility and adaptability to varying organisational structures and evolving access control needs
> Enhancement: Configurable User Role limit for Milvus

- .github/workflows/lint-test.yml
- charts/milvus/Chart.yaml
- charts/milvus/README.md
- charts/milvus/requirements.lock
- charts/milvus/requirements.yaml
- charts/milvus/values.yaml
- ct.yaml
> bump milvus version to v2.4.1

- charts/milvus/Chart.yaml
- charts/milvus/README.md
- charts/milvus/templates/configmap.yaml
- charts/milvus/templates/datacoord-deployment.yaml
- charts/milvus/templates/datanode-deployment.yaml
- charts/milvus/templates/indexcoord-deployment.yaml
- charts/milvus/templates/indexnode-deployment.yaml
- charts/milvus/templates/mixcoord-deployment.yaml
- charts/milvus/templates/proxy-deployment.yaml
- charts/milvus/templates/querycoord-deployment.yaml
- charts/milvus/templates/querynode-deployment.yaml
- charts/milvus/templates/rootcoord-deployment.yaml
- charts/milvus/templates/standalone-deployment.yaml
- charts/milvus/values.yaml
This PR adds an extra config field which allows users to use a completely custom ConfigMap for configuring Milvus. This is useful for situation where dynamic info needs to be added to the configmap for various reasons (example: configuring storage account ID based on some automatically provisioned resource).
> [milvus] Ability to use user specified ConfigMap for Milvus configuration

- charts/milvus/Chart.yaml
- charts/milvus/README.md
- charts/milvus/templates/datacoord-deployment.yaml
- charts/milvus/templates/datanode-deployment.yaml
- charts/milvus/templates/indexcoord-deployment.yaml
- charts/milvus/templates/indexnode-deployment.yaml
- charts/milvus/templates/mixcoord-deployment.yaml
- charts/milvus/templates/proxy-deployment.yaml
- charts/milvus/templates/querycoord-deployment.yaml
- charts/milvus/templates/querynode-deployment.yaml
- charts/milvus/templates/rootcoord-deployment.yaml
- charts/milvus/templates/standalone-deployment.yaml
- charts/milvus/values.yaml
1. Configuration Management Refine: We have removed the configuration merge before startup. Now, we will maintain three separate config files: `user.yaml`, `default.yaml`, and `milvus.yaml`. The `user.yaml` file can specify custom configurations and has the highest precedence. The `default.yaml` file specifies all dependencies configurations, which are automatically injected by the Helm chart. The `milvus.yaml` file is the default configuration, minted from the image.
2. Pulsar Upgrade: We have upgraded the Pulsar version from 2.8.2 to 2.9.5.
3. Milvus Upgrade: We have bumped the Milvus version from 2.4.5 to 2.4.6.
- [ x] Variables are documented in the README.md
> Bump milvus version to v2.4.6

- charts/milvus/Chart.yaml
- charts/milvus/templates/attu-ingress.yaml
- charts/milvus/templates/ingress.yaml
- charts/milvus/values.yaml
Since to EKS version 1.22, deprecated nginx kubernetes.io/ingress.class and we need to upgrade to using ingressClassName then i have create PR to do this 
> feat: add ingressClass

- charts/milvus/README.md
> chore: Compatibility Notice

- charts/milvus/Chart.yaml
- charts/milvus/README.md
- charts/milvus/templates/mixcoord-deployment.yaml
- charts/milvus/values.yaml
Use mixcoord instead of separate rootcoord, datacoord, querycoord and indexcoord.
- [ x] Variables are documented in the README.md
> Use mixcoord for milvus cluster by default

- charts/milvus/Chart.yaml
- charts/milvus/values.yaml
Attu v2.4.7 was released with two security patches, the user is asking to bump the version here as well. 
https://github.com/zilliztech/attu/issues/622
> [milvus] bump attu version to v2.4.7

- charts/milvus/Chart.yaml
- charts/milvus/README.md
- charts/milvus/values.yaml
> bump milvus to 2.4.10

- charts/milvus/Chart.yaml
- charts/milvus/templates/attu-ingress.yaml
This PR fixes the ingress classname for `Attu` and allows using 2 different ingress classes between `Milvus` and `Attu`.
- [?] Variables are documented in the README.md
> [milvus] Fix attu ingress class

- charts/milvus/Chart.yaml
- charts/milvus/templates/config.tpl
> [milvus] Fix missing clusterDomain in config template

- charts/milvus/Chart.yaml
- charts/milvus/README.md
- charts/milvus/templates/datacoord-deployment.yaml
- charts/milvus/templates/datanode-deployment.yaml
- charts/milvus/templates/indexcoord-deployment.yaml
- charts/milvus/templates/indexnode-deployment.yaml
- charts/milvus/templates/mixcoord-deployment.yaml
- charts/milvus/templates/proxy-deployment.yaml
- charts/milvus/templates/querycoord-deployment.yaml
- charts/milvus/templates/querynode-deployment.yaml
- charts/milvus/templates/rootcoord-deployment.yaml
- charts/milvus/values.yaml
To support datadog container autodiscovery, we need annotations attached directly to pods. The existing helm chart only supports custom annotations attached to services.
https://docs.datadoghq.com/containers/kubernetes/prometheus/
> [milvus] Support custom annotations in pod deployments

- charts/milvus/README.md
- docs/affinity-configuration-guide.md
- docs/node-selector-configuration-guide.md
- docs/node-selectors-vs-node-affinity.md
- docs/tolerations-configuration-guide.md
> doc: Affinity, Tolerations and Node Selector

- charts/milvus/Chart.yaml
- charts/milvus/requirements.lock
- charts/milvus/requirements.yaml
- charts/milvus/values.yaml
ref: https://github.com/milvus-io/milvus/issues/37929
> add pulsar chart alias, add some default values for pulsar3

- charts/milvus/Chart.yaml
- charts/milvus/README.md
- charts/milvus/templates/datanode-hpa.yaml
- charts/milvus/templates/indexnode-hpa.yaml
- charts/milvus/templates/proxy-hpa.yaml
- charts/milvus/templates/querynode-hpa.yaml
- charts/milvus/values.yaml
This PR enhances the Milvus Helm chart by incorporating scale-out deployment capabilities. It is based on the recommendations provided in the [scaleout documentation](https://milvus.io/docs/zh-hant/scaleout.md) and addresses the feedback outlined in [issue #100](https://github.com/zilliztech/milvus-helm/issues/100).
Key changes include:
- Setup HPA for stateless worker nodes include query node, data node, index node, and proxy.
- [v] Chart Version bumped
- [v] Variables are documented in the README.md
- [v] Title of the PR starts with chart name (e.g. `[mychartname]`)
- [v] PR only contains changes for one chart
> [milvus] Set hpa to allow queryNode, indexNode, proxy, and dataNode to automatically scale

- charts/milvus/README.md
- charts/milvus/templates/datanode-hpa.yaml
- charts/milvus/templates/indexnode-hpa.yaml
- charts/milvus/templates/proxy-hpa.yaml
- charts/milvus/templates/querynode-hpa.yaml
- charts/milvus/values.yaml
Following @haorenfsa 's suggestion, I added a memory threshold for the query node.
https://github.com/zilliztech/milvus-helm/pull/188
And adjust the default values ​​of the hpa template to be consistent with README.
- [v] Variables are documented in the README.md
- [v] Title of the PR starts with chart name (e.g. `[mychartname]`)
- [v] PR only contains changes for one chart
> [milvus] Added memory threshold for query node hpa and unified default settings for templates and README

- charts/milvus/templates/streamingnode-deployment.yaml
> feat: support empty dir for streaming node when message type if woodpecker

- charts/milvus/Chart.yaml
- charts/milvus/templates/attu-deployment.yaml
- charts/milvus/values.yaml
This PR adds the general `cluster.annotations` to attu deployment, to have feature parity with all the other deployments.
It also introduces `attu.annotations` for specific attu pod annotations.
it should fix #195 
I tried to respect the existing naming convention, please let me know if I missed something.
I couldn't find the README file where attu variables are documented.
> [milvus] added annotations to attu deployment and pod template

- charts/milvus/Chart.yaml
- charts/milvus/templates/attu-deployment.yaml
Syntax error at metadata.annotations in attu deployment.
> [milvus] Fix indentation of annotation in attu deployment

- charts/milvus/templates/attu-deployment.yaml
- charts/milvus/templates/datacoord-deployment.yaml
- charts/milvus/templates/datanode-deployment.yaml
- charts/milvus/templates/indexcoord-deployment.yaml
- charts/milvus/templates/indexnode-deployment.yaml
- charts/milvus/templates/mixcoord-deployment.yaml
- charts/milvus/templates/proxy-deployment.yaml
- charts/milvus/templates/querycoord-deployment.yaml
- charts/milvus/templates/querynode-deployment.yaml
- charts/milvus/templates/rootcoord-deployment.yaml
- charts/milvus/templates/standalone-deployment.yaml
- charts/milvus/templates/streamingnode-deployment.yaml
- charts/milvus/values.yaml
To give the option to define a container security context, at component level or define a general one. The same that it's currently done with the pod security context. 
Closes #216.
> feat #216: add container security contex to all containers and init containers

- charts/milvus/Chart.yaml
- charts/milvus/README.md
- charts/milvus/templates/attu-route.yaml
- charts/milvus/values.yaml
OpenShift users currently have to use Kubernetes Ingress to expose the Attu UI interface. While this works, OpenShift Routes can be the preferred way to expose services in OpenShift environments, offering:
- Built-in TLS termination and certificate management
- Integration with OpenShift's certificate management
- Native support for OpenShift's security features
- Better integration with OpenShift's routing layer
This PR introduces OpenShift Route support as an alternative to Kubernetes Ingress for the Attu UI interface. Users can now choose between:
1. Using Kubernetes Ingress (existing behavior)
2. Using OpenShift Route (new feature)
The implementation is non-breaking and opt-in, maintaining compatibility with existing deployments. Route configuration supports all major features …
> [milvus] -  Add OpenShift route support for Attu UI

- charts/milvus/Chart.yaml
- charts/milvus/templates/indexnode-deployment.yaml
- charts/milvus/templates/querynode-deployment.yaml
- charts/milvus/values.yaml
This PR adds `runtimeClassName` as an optional configuration for the `queryNode` and `indexNode` deployments. This allows users to specify alternate runtimes, such as NVIDIA's runtime for GPU workloads.
This is a replacement for #221. It is rebased onto the latest upstream `master`, includes the proper chart version bump to `4.2.56`, and has the correct DCO sign-off to satisfy contribution requirements.
This PR will close #220.
> fixes #220: Adds runtimeClassName option to query and index deployments

- charts/milvus/Chart.yaml
- charts/milvus/values.yaml
This pull request updates the Milvus Helm chart dependencies to use images from the `bitnamilegacy` repository instead of the standard `bitnami` repository, and bumps the chart version. These changes ensure continued access to required container images and improve compatibility.
Dependency image repository updates:
* Changed the Kafka image repository from `bitnami/kafka` to `bitnamilegacy/kafka` and updated the tag to `3.1.0` in `values.yaml`.
* Updated Kafka exporter and JMX exporter image repositories from `bitnami` to `bitnamilegacy` and adjusted tags accordingly in `values.yaml`.
* Set Zookeeper image to `bitnamilegacy/zookeeper` with tag `3.7.0` in `values.yaml`.
Chart version bump:
* Increased the chart version from `5.0.0` to `5.0.1` in `Chart.yaml` to reflect these dependency …
> update bitnami image to use legacy bitnami repo
