- .github/workflows/lint-test.yml
- .github/workflows/release.yml
- README.md
- charts/milvus/Chart.yaml
- charts/milvus/README.md
- charts/milvus/requirements.lock
- charts/milvus/requirements.yaml
/cc @zwd1208 @Bennu-Li @locustbaby 
> Refine doc link

- charts/milvus/Chart.yaml
- charts/milvus/README.md
- charts/milvus/templates/config.tpl
- charts/milvus/values.yaml
/cc @zwd1208 @Bennu-Li @locustbaby 
- [x ] Variables are documented in the README.md
> Add new message queue natsmq for milvus standalone

- charts/milvus/Chart.yaml
- charts/milvus/README.md
- charts/milvus/values.yaml
> Bump milvus version to 2.2.14

- charts/milvus/Chart.yaml
- charts/milvus/templates/_helpers.tpl
- charts/milvus/templates/config.tpl
Make the coord's activestandby behavior consistent.
> Fix-mixcoord-activeStandby

- README.md
> Refine artifacthub.io link and milvus logo

- charts/milvus/README.md
- charts/milvus/templates/config.tpl
- charts/milvus/values.yaml
> [milvus] S3 miss the region/useVirtualHost settings

- .github/mergify.yml
- .github/workflows/checks.yaml
- .github/workflows/lint-test.yml
resolve the conflict of mergify's bot
> tune mergify's rules

- charts/milvus/Chart.yaml
- charts/milvus/values.yaml
> Refine etcd probe timeout

- charts/milvus/Chart.yaml
- charts/milvus/README.md
- charts/milvus/values.yaml
> Bump milvus version to v2.3.2

- charts/milvus/Chart.yaml
- charts/milvus/README.md
- charts/milvus/values.yaml
/cc @zwd1208 @Bennu-Li @locustbaby 
- [x ] Variables are documented in the README.md
> Bump milvus version to v2.3.3

- charts/milvus/Chart.yaml
- charts/milvus/templates/config.tpl
> [milvus] 2.3.3 config common.storageType: remote to support azure

- charts/milvus/Chart.yaml
- charts/milvus/README.md
- charts/milvus/values.yaml
> Bump milvus version to v2.3.4

- charts/milvus/Chart.yaml
- charts/milvus/README.md
- charts/milvus/values.yaml
> Bump milvus version to v2.3.5

- charts/milvus/Chart.yaml
- charts/milvus/values.yaml
> update etcd image to support arm

- charts/milvus/Chart.yaml
- charts/milvus/README.md
- charts/milvus/values.yaml
> Bump milvus version to v2.3.6

- charts/milvus/Chart.yaml
- charts/milvus/README.md
- charts/milvus/values.yaml
> Reset milvus version to v2.3.5

- charts/milvus/Chart.yaml
- charts/milvus/README.md
- charts/milvus/values.yaml
> Bump milvus version to v2.3.7

- charts/milvus/Chart.yaml
- charts/milvus/README.md
- charts/milvus/values.yaml
> Bump milvus version to v2.38

- charts/milvus/Chart.yaml
- charts/milvus/README.md
- charts/milvus/values.yaml
> Bump milvus version to v2.3.9

- charts/milvus/Chart.yaml
- charts/milvus/README.md
- charts/milvus/values.yaml
> Bump milvus version to v2.3.10

- charts/milvus/Chart.yaml
- charts/milvus/README.md
- charts/milvus/values.yaml
> Bump milvus version to v2.3.11

- charts/milvus/Chart.yaml
- charts/milvus/README.md
- charts/milvus/values.yaml
> bump milvus version to v2.3.12

- charts/milvus/Chart.yaml
- charts/milvus/README.md
- charts/milvus/values.yaml
> remove minio gateway

- charts/milvus/Chart.yaml
- charts/milvus/templates/config.tpl
> Fix config.tpl after removing minio gateway mode

- charts/milvus/Chart.yaml
- charts/milvus/README.md
- charts/milvus/values.yaml
> Bump milvus version to v2.3.13

- charts/milvus/Chart.yaml
- charts/milvus/README.md
- charts/milvus/values.yaml
> bump milvus version to v2.4.0

- .github/workflows/release.yml
> Fix release chart action

- charts/milvus/Chart.yaml
- charts/milvus/values.yaml
These enhancements will improve following key features:
- Better collection loading
- Pagination
- Custom filter expressions
- Fixed count sort problem on collections
- Clean console errors  etc
> [milvus-4.1.31] Enhanced Attu Component

- charts/milvus/Chart.yaml
- charts/milvus/README.md
- charts/milvus/values.yaml
> bump milvus version to v2.4.3

- charts/milvus/Chart.yaml
- charts/milvus/README.md
- charts/milvus/values.yaml
> bump milvus version to v2.4.4

- charts/milvus/Chart.yaml
- charts/milvus/README.md
- charts/milvus/values.yaml
> bump milvus version to v2.4.5

- charts/milvus/templates/_helpers.tpl
- charts/milvus/values.yaml
修复 helper 中的一些明显错误，添加 helper 中引用但是在 values.yaml 中不存在的 nameOverridem, fullnameOverride
> Fix template helper file

- charts/milvus/Chart.yaml
- charts/milvus/templates/config.tpl
/cc @yellow-shine @locustbaby @haorenfsa 
> Fix external s3 config

- charts/milvus/values.yaml
> update attu version to 2.4.6

- charts/milvus/Chart.yaml
- charts/milvus/README.md
- charts/milvus/templates/config.tpl
- charts/milvus/values.yaml
> Bump to 2.4.7

- charts/milvus/Chart.yaml
- charts/milvus/README.md
- charts/milvus/values.yaml
> bump milvus to 2.4.9

- charts/milvus/Chart.yaml
- charts/milvus/README.md
- charts/milvus/values.yaml
> bump milvus to 2.4.11

- charts/milvus/Chart.yaml
- charts/milvus/README.md
- charts/milvus/values.yaml
> bump milvus to 2.4.12

- charts/milvus/Chart.yaml
- charts/milvus/README.md
- charts/milvus/values.yaml
> bump milvus to 2.4.13

- charts/milvus/Chart.yaml
- charts/milvus/templates/datacoord-deployment.yaml
- charts/milvus/templates/datanode-deployment.yaml
- charts/milvus/templates/indexcoord-deployment.yaml
- charts/milvus/templates/indexnode-deployment.yaml
- charts/milvus/templates/mixcoord-deployment.yaml
- charts/milvus/templates/proxy-deployment.yaml
- charts/milvus/templates/querycoord-deployment.yaml
- charts/milvus/templates/querynode-deployment.yaml
- charts/milvus/templates/rootcoord-deployment.yaml
- charts/milvus/templates/streamingnode-deployment.yaml
- charts/milvus/templates/streamingnode-svc.yaml
/cc @yellow-shine @locustbaby 
> Fix upgrade error with --reuse-values

- charts/milvus/Chart.yaml
- charts/milvus/README.md
- charts/milvus/values.yaml
> bump milvus to 2.4.13-hotfix

- charts/milvus/Chart.yaml
- charts/milvus/README.md
- charts/milvus/values.yaml
> bump milvus to 2.4.14

- charts/milvus/Chart.yaml
- charts/milvus/README.md
- charts/milvus/values.yaml
> bump milvus to 2.4.15

- charts/milvus/README.md
> doc: update link

- charts/milvus/Chart.yaml
- charts/milvus/README.md
- charts/milvus/values.yaml
> release tag 2.4.16

- README.md
- charts/milvus/Chart.yaml
- charts/milvus/README.md
update readme for 4.2.21+ Compatibility Notice
> update readme for 4.2.21+ Compatibility Notice

- charts/milvus/Chart.yaml
- charts/milvus/README.md
- charts/milvus/values.yaml
> release tag 2.4.17

- charts/milvus/Chart.yaml
- charts/milvus/README.md
- charts/milvus/values.yaml
> release tag 2.5.0-beta

- charts/milvus/Chart.yaml
- charts/milvus/values.yaml
> enable pulsarv3 & disable pulsarv2 by default

- charts/milvus/Chart.yaml
- charts/milvus/values.yaml
> Fix pulsar values

- README.md
- charts/milvus/Chart.yaml
- charts/milvus/README.md
> change dep pulsar to zilliz pulsarv2 chart

- charts/milvus/templates/datacoord-deployment.yaml
- charts/milvus/templates/datanode-deployment.yaml
- charts/milvus/templates/indexcoord-deployment.yaml
- charts/milvus/templates/indexnode-deployment.yaml
- charts/milvus/templates/mixcoord-deployment.yaml
- charts/milvus/templates/proxy-deployment.yaml
- charts/milvus/templates/querycoord-deployment.yaml
- charts/milvus/templates/querynode-deployment.yaml
- charts/milvus/templates/rootcoord-deployment.yaml
- charts/milvus/templates/standalone-deployment.yaml
- charts/milvus/templates/streamingnode-deployment.yaml
- charts/milvus/values.yaml
support: https://github.com/milvus-io/milvus/discussions/38613
> feat: support topologySpreadConstraints

- charts/milvus/Chart.yaml
- charts/milvus/README.md
- charts/milvus/values.yaml
> release tag 2.5.1

- charts/milvus/Chart.yaml
- charts/milvus/README.md
- charts/milvus/values.yaml
> release tag 2.5.2

- charts/milvus/Chart.yaml
- charts/milvus/README.md
- charts/milvus/values.yaml
> release tag 2.5.3

- charts/milvus/Chart.yaml
- charts/milvus/README.md
- charts/milvus/values.yaml
> release tag v2.5.4

- charts/milvus/Chart.yaml
- charts/milvus/templates/datacoord-deployment.yaml
- charts/milvus/templates/datanode-deployment.yaml
- charts/milvus/templates/indexcoord-deployment.yaml
- charts/milvus/templates/indexnode-deployment.yaml
- charts/milvus/templates/mixcoord-deployment.yaml
- charts/milvus/templates/proxy-deployment.yaml
- charts/milvus/templates/querycoord-deployment.yaml
- charts/milvus/templates/querynode-deployment.yaml
- charts/milvus/templates/rootcoord-deployment.yaml
- charts/milvus/templates/standalone-deployment.yaml
- charts/milvus/templates/streamingnode-deployment.yaml
> change liveness probe to tcpSocket

- charts/milvus/Chart.yaml
- charts/milvus/values.yaml
> update attu version to 2.5.3

- charts/milvus/Chart.yaml
- charts/milvus/README.md
- charts/milvus/values.yaml
> release tag 2.5.5

- charts/milvus/Chart.yaml
- charts/milvus/README.md
- charts/milvus/values.yaml
> release tag 2.5.6

- charts/milvus/Chart.yaml
- charts/milvus/README.md
- charts/milvus/values.yaml
> release tag 2.5.7

- charts/tei/.helmignore
- charts/tei/Chart.yaml
- charts/tei/README.md
- charts/tei/ci/tei-mininum-values.yaml
- charts/tei/templates/_helpers.tpl
- charts/tei/templates/headless-service.yaml
- charts/tei/templates/service.yaml
- charts/tei/templates/serviceaccount.yaml
- charts/tei/templates/statefulset.yaml
- charts/tei/values.yaml
> add tei chart

- charts/milvus/Chart.yaml
- charts/milvus/templates/config.tpl
> fix message queue config

- charts/milvus/templates/attu-deployment.yaml
- charts/milvus/templates/datacoord-deployment.yaml
- charts/milvus/templates/datanode-deployment.yaml
- charts/milvus/templates/indexcoord-deployment.yaml
- charts/milvus/templates/indexnode-deployment.yaml
- charts/milvus/templates/mixcoord-deployment.yaml
- charts/milvus/templates/proxy-deployment.yaml
- charts/milvus/templates/querycoord-deployment.yaml
- charts/milvus/templates/querynode-deployment.yaml
- charts/milvus/templates/rootcoord-deployment.yaml
- charts/milvus/templates/standalone-deployment.yaml
- charts/milvus/templates/streamingnode-deployment.yaml
- charts/milvus/values.yaml
- docs/security-context-configuration-guide.md
> feat: support security context

- charts/milvus/Chart.yaml
- charts/milvus/README.md
- charts/milvus/values.yaml
> release tag 2.5.8

- charts/milvus/Chart.yaml
- charts/milvus/README.md
- charts/milvus/values.yaml
> release tag 2.5.10

- charts/milvus/Chart.yaml
- charts/milvus/README.md
- charts/milvus/values.yaml
> release tag 2.5.11

- charts/milvus/Chart.yaml
- charts/milvus/README.md
- charts/milvus/values.yaml
> release tag 2.5.12

- charts/milvus/README-TEI.md
- charts/tei/README.md
> [TEI]Update TEI readme

- charts/milvus/Chart.yaml
- charts/milvus/values.yaml
- charts/minio/README.md
> update kafka-exporter image

- charts/milvus/values.yaml
- charts/minio/Chart.yaml
> update minio version

- charts/milvus/Chart.yaml
- charts/milvus/README.md
- charts/milvus/values.yaml
> release tag 2.5.15

- charts/milvus/Chart.yaml
- charts/milvus/README.md
- charts/milvus/values.yaml
> release tag 2.5.16

- charts/milvus/Chart.yaml
- charts/milvus/README.md
- charts/milvus/values.yaml
> release tag 2.6.1

- charts/milvus/Chart.yaml
- charts/milvus/README.md
- charts/milvus/values.yaml
> Release tag 2.6.2
